# Render

###
# **************
# Localhost

# Weapons
DELETE http://localhost:3000/api/weapons/635443cc2c9e7ad4d2e1f06a HTTP/1.1
###

# Valid Information
PUT http://localhost:3000/api/weapons/635444ec9c89a5e6be32842c HTTP/1.1
content-type: application/json

{
    "name": "Valid-Test",
    "rarity": 5,
    "type": "Sword",
    "passiveAbility": "Testing an api"
}
###

# Invalid Information
PUT http://localhost:3000/api/weapons/635444ec9c89a5e6be32842c HTTP/1.1
content-type: application/json

{
    "name": "Fail-Test",
    "passiveAbility": "Testing an api"
}
###

# Valid Information
POST http://localhost:3000/api/weapons HTTP/1.1 
content-type: application/json

{
    "name": "Valid-Test",
    "rarity": 5,
    "type": "Sword",
    "passiveAbility": "Testing an api"
}
###
# Invalid Information
POST http://localhost:3000/api/weapons HTTP/1.1 
content-type: application/json

{
    "name": "Fail-Test",
    "rarity": "5"
}
###

GET http://localhost:3000/api/weapons
###