# Localhost
GET http://localhost:3000/api/characters
###
# Real Id
GET http://localhost:3000/api/characters/634a0b8eb384ec19f6b1e23e
###
# Fake Id
GET http://localhost:3000/api/characters/6349f631f4e56b197afb8777
###